[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "algo-edu"
version = "0.1.0"
description = "An educational Python toolkit for learning and exploring classic algorithms"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]

keywords = [
    "algorithms",
    "data structures",
    "computer science",
    "learning",
    "education",
    "searching",
    "sorting"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Education",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/yuki-sf/algo-edu"
Repository = "https://github.com/yuki-sf/algo-edu"

[tool.setuptools.packages.find]
where = ["src"]